'use strict';
const $=id=>document.getElementById(id);
const people=[
['Kco','El presidente de la Desdepida','Reorganiza: completa una entrega de hielo a distancia.','Camina un 8% más lento.','DECRETO'],
['Gota','Mi casa, mis reglas','Cocina y repara un 25% más rápido. Su poder conecta el generador durante el apagón.','Lleva un solo objeto por viaje.','LO HAGO YO'],
['Edu','A las 19 me retiro','Activa 8 segundos de energía antes de conectar con Ipa.','Después necesita una siesta de 2 segundos.','ANTES DE LAS 19'],
['Peni','999 mensajes después','Su poder trae y enciende velas durante el apagón; fuera de él duplica un trabajo.','La primera recogida tarda 3 segundos extra.','APARECIÓ'],
['Mendo','Fernet, paz y Racing','Los fondos duran la mitad. Su poder enfría la bebida a distancia.','Camina un 8% más lento.','INMUTABLE'],
['Tute','Viernes, 22 hs','Activa 8 segundos de velocidad doble.','Lleva un solo objeto por viaje.','MODO GAMER'],
['Rama','El fiscal del asado','Cada reposera reparada vale 40 puntos extra. Su poder repara una.','Las reparaciones tardan 1 segundo más.','LIBRO DE QUEJAS'],
['Juancho','Supervisión desde España','Ve cuándo viene el próximo evento. Su poder resuelve el apagón.','Su poder tarda 3 segundos en llegar.','CONEXIÓN REMOTA'],
['Toni','Asado.exe','Repetir un tipo de trabajo acelera su ejecución. Su poder llena la mochila.','Cambiar de trabajo reinicia la mejora.','OPTIMIZAR'],
['Corcho','Sale encuesta. Soy baja.','Elige una ayuda: hielo o reparación.','Después de votar trabaja más lento durante 8 segundos.','SALE ENCUESTA']];
const badgeDefs=[['approved','🏛️','La Comisión aprueba'],['ice','🧊','¿El hielo de quién era?'],['seats','🪑','Amenities sin demandas'],['power','⚡','Gota te lo soluciona'],['chef','🔥','Ni un carbón de más'],['legend','🏆','Asado legendario'],['corcho','📊','Esta vez vino'],['all','🤝','La banda completa']];
let saved;try{saved=JSON.parse(localStorage.getItem('chichachos-v1'))||{}}catch{saved={}}saved.badges=Array.isArray(saved.badges)?saved.badges:[];saved.played=Array.isArray(saved.played)?saved.played:[];saved.best=Number(saved.best)||0;
let selected=0,g=null,last=0,sound=false,audioCtx,toastUntil=0;
const keys=new Set(),images={};people.forEach(p=>{const im=new Image();im.src=`characters/${p[0]}.png`;images[p[0]]=im;});
const stations=[{id:'supply',x:115,y:150,icon:'📦',name:'PROVISIONES'},{id:'grill',x:460,y:115,icon:'🔥',name:'PARRILLA'},{id:'ice',x:820,y:150,icon:'🧊',name:'HIELO'},{id:'fridge',x:820,y:400,icon:'🍻',name:'BEBIDAS'},{id:'seats',x:460,y:425,icon:'🪑',name:'REPOSERAS'},{id:'power',x:115,y:420,icon:'⚡',name:'GENERADOR'},{id:'candles',x:115,y:285,icon:'🕯️',name:'ALMACÉN'}];
function persist(){try{localStorage.setItem('chichachos-v1',JSON.stringify(saved));return true}catch{return false}}
function show(id){['lobby','play','result'].forEach(s=>$(s).hidden=s!==id);window.scrollTo(0,0)}
function renderLobby(){ $('roster').innerHTML=people.map((p,i)=>`<button class="character ${i===selected?'selected':''}" data-person="${i}" aria-pressed="${i===selected}"><img src="characters/${p[0]}.png" alt="${p[0]}"><b>${p[0]}</b></button>`).join('');const p=people[selected];$('profile').innerHTML=`<h3>${p[0]} · ${p[1]}</h3><p class="plus">+ ${p[2]}</p><p>− ${p[3]}</p>`;$('record').textContent=`TU RÉCORD: ${saved.best.toLocaleString('es-AR')} PTS`;$('collection').innerHTML=badgeDefs.map(b=>`<span class="badge ${saved.badges.includes(b[0])?'':'locked'}">${saved.badges.includes(b[0])?b[1]:'🔒'} ${b[2]}</span>`).join('');}
$('roster').addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b){selected=+b.dataset.person;renderLobby()}});
function beep(f=550){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.frequency.value=f;v.gain.setValueAtTime(.04,audioCtx.currentTime);v.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.connect(v);v.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}catch{}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`SONIDO: ${sound?'ON':'OFF'}`;beep()};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastUntil=performance.now()+4200}
function daily(){return new Date().toLocaleDateString('sv-SE',{timeZone:'America/Argentina/Buenos_Aires'})}
function start(tutorial=false){const date=daily();let seed=[...date].reduce((a,c)=>a+c.charCodeAt(0),0);g={tutorial,step:0,eduRest:false,person:people[selected][0],date,t:180,score:0,x:460,y:290,target:null,job:null,cargo:[],food:0,drinks:0,seats:0,cold:80,minCold:80,cook:0,ready:false,burns:0,drunk:0,boost:0,cooldown:0,slow:0,lock:0,pending:0,first:true,double:false,lastJob:'',streak:0,outage:false,candles:false,fixed:false,paused:false,done:false,events:[{at:145,type:seed%2?'ice':'priority'},{at:105,type:'outage'},{at:55,type:seed%2?'priority':'ice'}],eventIndex:0,iceMoved:false,priority:0,lastPenalty:0,earned:[]};stations.find(s=>s.id==='ice').y=150;keys.clear();show('play');$('player-name').textContent=`${g.person} se hace cargo`;$('ability').textContent=people[selected][4];toast('Primero: provisiones → parrilla. Después buscá hielo mientras se cocina.');last=performance.now();$('board').focus();updateHud();}
$('start').onclick=()=>start(!saved.tutorial);$('practice').onclick=()=>start(true);
const lesson=[['supply','1/6 · Tocá PROVISIONES para buscar carne y carbón.'],['grill','2/6 · Tocá PARRILLA para dejar la carne cocinando.'],['ice','3/6 · La carne se cocina sola. Tocá HIELO para buscar una bolsa.'],['fridge','4/6 · Tocá BEBIDAS para entregar el hielo.'],['seats','5/6 · Tocá REPOSERAS para reparar una mientras esperás.'],['grill','6/6 · Tocá PARRILLA para retirar la carne lista.']];
$('tutorial-play').onclick=()=>{$('tutorial-done').close();saved.tutorial=true;persist();start(false)};$('tutorial-done').addEventListener('cancel',e=>e.preventDefault());
function capacity(){return ['Gota','Tute'].includes(g.person)?1:2}
function choose(id){if(!g||g.done||g.paused)return;g.job=null;const s=stations.find(s=>s.id===id);g.target=s;}
$('station-buttons').innerHTML=stations.map(s=>`<button data-station="${s.id}">${s.icon} ${s.name.toLowerCase()}</button>`).join('');$('station-buttons').onclick=e=>{const b=e.target.closest('[data-station]');if(b)choose(b.dataset.station)};
$('board').onclick=e=>{if(!g||g.paused||g.done)return;const r=$('board').getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*560/r.height;const s=stations.find(s=>Math.hypot(s.x-x,s.y-y)<95);if(s)choose(s.id);else{g.job=null;g.target={x,y}}};
function begin(s){if(g.tutorial&&s.id!==lesson[g.step][0])return toast('Seguí la flecha y la instrucción de arriba.');let duration=1.2,kind=s.id;if(kind==='candles'){if(!g.outage)return toast('Las velas se necesitan durante el apagón.');if(g.candles)return toast('Las velas ya están encendidas. Falta el generador.');duration=g.person==='Peni'?1:3;}if(kind==='supply'||kind==='ice'){if(g.cargo.length>=capacity())return toast('Mochila llena. Entregá en parrilla o bebidas.');duration=1.1;if(g.person==='Peni'&&g.first)duration+=3;}
if(kind==='grill'){if(g.ready){duration=.8;kind='serve'}else if(g.cook>0){toast('Se está cocinando. Aprovechá para hacer otra tarea.');return}else if(!g.cargo.includes('carne'))return toast('Buscá carne y carbón en PROVISIONES.');else duration=1.8;}
if(kind==='fridge'&&!g.cargo.includes('hielo'))return toast('Buscá una bolsa en HIELO.');
if(kind==='seats'){if(g.seats>=4)return toast('Las cuatro reposeras están listas.');duration=g.person==='Rama'?4:3;}
if(kind==='power'){if(!g.outage)return toast('Hay luz. Todo en orden.');duration=4;}
if(g.person==='Gota'&&['grill','seats','power'].includes(kind))duration*=.75;
if(g.person==='Toni'&&g.lastJob===kind)duration*=Math.max(.55,1-g.streak*.15);
if(g.slow>0)duration*=1.6;g.job={kind,total:duration,left:duration};}
function points(n){g.score+=Math.round(n*(g.priority>0?1.5:1));beep();}
function finishJob(){const kind=g.job.kind;g.job=null;g.streak=g.lastJob===kind?g.streak+1:0;g.lastJob=kind;
if(kind==='supply'||kind==='ice'){g.cargo.push(kind==='supply'?'carne':'hielo');g.first=false;}
if(kind==='grill'){g.cargo.splice(g.cargo.indexOf('carne'),1);g.cook=g.tutorial?3:g.person==='Gota'?10:14;toast('Carne al fuego. Volvé cuando diga LISTA.');}
if(kind==='serve'){g.ready=false;g.cook=0;g.food++;points(250);toast('¡Sale una tanda! +250 puntos');}
if(kind==='fridge'){g.cargo.splice(g.cargo.indexOf('hielo'),1);g.cold=Math.min(100,g.cold+45);g.drinks++;points(130);}
if(kind==='seats'){g.seats++;points(g.person==='Rama'?220:180);}
if(kind==='candles'){g.candles=true;points(120);toast('Peni tenía razón: velas del almacén. Hay luz, pero la bebida sigue calentándose.');}
if(kind==='power'){g.outage=false;g.fixed=true;points(180);toast('Volvió la luz. La juntada sigue.');}
if(g.tutorial){g.step++;if(g.step>=lesson.length){g.paused=true;$('tutorial-done').showModal();return}}
if(g.double&&!['supply','ice','grill'].includes(kind)){points(kind==='serve'?250:130);g.double=false;toast('¡Peni apareció! Trabajo con bonus.');}
}
function penalty(){g.score=Math.max(0,g.score-60);g.lastPenalty=60;g.drunk=g.person==='Mendo'?4:8;toast('Se quemó la carne. −60 puntos y fondo virtual: caminás con dificultad.');beep(170)}
function helpSeats(){if(g.seats<4){g.seats++;points(g.person==='Rama'?220:180);toast('Reposera reparada. Amenities agradece.')}else{g.cold=Math.min(100,g.cold+35);toast('Reposeras listas: ayudaste con el frío.')}}
function ability(){if(!g||g.done||g.paused||g.cooldown>0||g.tutorial)return;const p=g.person;if(p==='Juancho'&&!g.outage)return toast('Guardá la conexión para el corte de luz.');g.cooldown=45;
if(p==='Kco'||p==='Mendo'){g.cold=Math.min(100,g.cold+45);g.drinks++;points(130);toast(p==='Kco'?'Por decreto: el hielo es de bebidas.':'Fernet a temperatura reglamentaria.');}
if(p==='Gota'&&g.outage){g.outage=false;g.fixed=true;points(180);toast('Gota consiguió el generador. Volvieron la luz y la heladera.');}else if(p==='Gota'||p==='Rama')helpSeats();if(p==='Edu'){g.boost=8;g.eduRest=true;toast('18:59 · ¡Último esfuerzo! 8 segundos de velocidad doble y después siesta.');}
if(p==='Peni'){if(g.outage&&!g.candles){g.candles=true;points(120);toast('Peni volvió del almacén con velas. ¡Ahora vemos! Falta resolver el frío.');}else{g.double=true;toast('El próximo trabajo terminado recibe puntos extra.');}}
if(p==='Tute'){g.boost=8;toast('22 hs. Esta vez sí se conectó.');}
if(p==='Juancho'){g.pending=3;toast('Conectando con España… solución en 3 segundos.');}
if(p==='Toni'){while(g.cargo.length<capacity())g.cargo.push(g.cargo.includes('carne')?'hielo':'carne');toast('Mochila optimizada. A ejecutar.');}
if(p==='Corcho'){g.paused=true;const d=document.createElement('dialog');d.innerHTML='<h2>Sale encuesta</h2><p>¿Qué necesita la banda?</p><button class="primary" data-vote="ice">HIELO</button> <button class="secondary" data-vote="seats">REPOSERA</button>';document.body.append(d);d.addEventListener('cancel',e=>e.preventDefault());d.onclick=e=>{if(!e.target.dataset.vote)return;if(e.target.dataset.vote==='ice'){g.cold=Math.min(100,g.cold+45);g.drinks++;points(130)}else helpSeats();g.slow=8;g.paused=false;d.close();d.remove();toast('Encuesta cerrada. Soy baja: trabajás más lento durante 8 segundos.');};d.showModal();}}
$('ability').onclick=ability;
function event(type){if(type==='outage'){g.outage=true;toast('⚡ CORTE DE LUZ. Velas en el almacén o generador. ¡La bebida se calienta!');}if(type==='ice'){g.iceMoved=!g.iceMoved;const s=stations.find(s=>s.id==='ice');s.y=g.iceMoved?270:150;toast('🧊 El hielo era de amenities. Movieron las bolsas al costado del patio.');}if(type==='priority'){g.priority=18;toast('🏛️ La Comisión exige resultados. ¡Puntos ×1,5 por 18 segundos!');}}
function pause(){if(!g||g.done||g.paused)return;g.paused=true;keys.clear();$('pause-dialog').showModal()}
$('pause').onclick=pause;$('resume').onclick=()=>{$('pause-dialog').close();g.paused=false;keys.clear()};$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();$('resume').click()});$('quit').onclick=()=>{$('pause-dialog').close();g.done=true;show('lobby');renderLobby()};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
window.addEventListener('keydown',e=>{if(!g||g.done||$('play').hidden)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if($('pause-dialog').open)$('resume').click();else pause();return}if(g.paused)return;const k=e.key.toLowerCase();keys.add(k);if(k===' '&&!e.repeat)ability();if(k==='e'&&!e.repeat&&!g.job){const s=stations.find(s=>Math.hypot(s.x-g.x,s.y-g.y)<95);if(s)begin(s)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();pause()});
function tick(dt){if(!g||g.done||g.paused)return;if(!g.tutorial)g.t=Math.max(0,g.t-dt);for(const k of ['drunk','boost','cooldown','slow','lock','priority'])g[k]=Math.max(0,g[k]-dt);if(g.pending>0){g.pending-=dt;if(g.pending<=0&&g.outage){g.outage=false;g.fixed=true;points(180);toast('España solucionó el apagón.');}}
if(g.eduRest&&g.boost<=0){g.eduRest=false;g.lock=2;toast('19:00 · Edu conecta con Ipa. Siesta de 2 segundos.');}if(!g.tutorial)g.cold=Math.max(0,g.cold-dt*(g.outage?1.8:.43));g.minCold=Math.min(g.minCold,g.cold);if(!g.tutorial&&g.eventIndex<g.events.length&&g.t<=g.events[g.eventIndex].at)event(g.events[g.eventIndex++].type);
if(g.cook>0&&!g.ready){g.cook-=dt;if(g.cook<=0){g.ready=true;g.cook=11;toast(g.tutorial?'🔥 Carne lista. En el tutorial no se quema: seguí los pasos.':'🔥 ¡CARNE LISTA! Tenés 11 segundos para retirarla.');beep(800)}}else if(g.ready&&!g.tutorial){g.cook-=dt;if(g.cook<=0){g.ready=false;g.cook=0;g.burns++;penalty()}}
if(g.lock<=0){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){g.target=null;g.job=null;}else if(g.target){dx=g.target.x-g.x;dy=g.target.y-g.y;if(Math.hypot(dx,dy)<65){const s=g.target;g.target=null;if(s.id)begin(s);dx=dy=0;}}
const mag=Math.hypot(dx,dy);if(mag){let speed=175*(['Kco','Mendo'].includes(g.person)?.92:1)*(g.boost>0?2:1)*(g.drunk>0?.68:1);g.x=Math.max(45,Math.min(915,g.x+dx/mag*speed*dt));g.y=Math.max(65,Math.min(510,g.y+dy/mag*speed*dt));}if(g.job){g.job.left-=dt;if(g.job.left<=0)finishJob();}}
updateHud();if(g.t<=0)end();}
function updateHud(){if(!g)return;if(g.tutorial&&g.step>=lesson.length)return;$('mode-label').textContent=g.tutorial?'ENTRENAMIENTO · SIN RELOJ':'OPERATIVO ASADO 2026';$('mission').textContent=g.tutorial?lesson[g.step][1]:g.lock>0?'💤 19:00 · Conectando con Ipa…':g.ready?'🔥 ¡Carne lista! Tocá PARRILLA antes de que se queme.':g.outage&&!g.candles?'⚡ Sin luz: ALMACÉN para velas o GENERADOR para restaurar todo.':g.outage?'⚡ Las velas iluminan. Conectá el GENERADOR para enfriar las bebidas.':g.cargo.includes('carne')&&!g.cook?'🔥 Llevá la carne a PARRILLA.':g.cargo.includes('hielo')?'🧊 Entregá el hielo en BEBIDAS.':g.cook>0?'🪑 Mientras se cocina: buscá HIELO o repará REPOSERAS.':'📦 Buscá PROVISIONES para empezar otra tanda de asado.';$('timer').textContent=`${Math.floor(Math.ceil(g.t)/60)}:${String(Math.ceil(g.t)%60).padStart(2,'0')}`;if(g.tutorial)$('timer').textContent='∞';$('timer').classList.toggle('urgent',g.t<30);$('score').textContent=g.score;$('food-goal').textContent=`🔥 Tandas ${g.food}/3`;$('drink-goal').textContent=`🧊 Entregas ${g.drinks}/3 · frío ${Math.round(g.cold)}%`;$('seat-goal').textContent=`🪑 Reposeras ${g.seats}/4`;$('cargo').textContent=g.cargo.length?g.cargo.map(c=>c==='carne'?'📦 CARNE + CARBÓN':'🧊 HIELO').join(' · '):'MANOS LIBRES';$('ability').disabled=g.cooldown>0||g.tutorial;$('ability').textContent=g.cooldown>0?`${people[selected][4]} · ${Math.ceil(g.cooldown)}s`:people[selected][4];$('hint').textContent=g.job?'Trabajando… podés moverte para cancelar.':g.drunk>0?'Fondo virtual: velocidad reducida por unos segundos.':g.person==='Juancho'&&g.eventIndex<g.events.length?`Próximo evento en ${Math.ceil(g.t-g.events[g.eventIndex].at)}s. Tocá una estación.`:'Tocá una estación: caminás y trabajás automáticamente.';}
const ctx=$('board').getContext('2d');function box(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}function label(t,x,y,size=13,color='#edf0dc'){ctx.fillStyle=color;ctx.font=`600 ${size}px sans-serif`;ctx.textAlign='center';ctx.fillText(t,x,y)}
function stationArt(s,active){
const x=s.x,y=s.y;ctx.save();ctx.translate(x,y);ctx.shadowColor='#0006';ctx.shadowBlur=8;ctx.shadowOffsetY=6;
if(s.id==='supply'){box(-48,-42,96,62,5,'#925b32');box(-43,-37,86,49,3,'#bd884e');for(let i=-35;i<40;i+=22)box(i,-35,4,47,0,'#825633');box(-29,-28,29,18,7,'#b84d3d');box(5,-25,27,21,7,'#783b31');label('CARBÓN',0,8,10,'#392e22');}
if(s.id==='grill'){box(-61,-39,122,70,5,'#a35e3f');for(let row=0;row<3;row++)for(let i=0;i<5;i++)box(-58+i*24+(row%2?8:0),-36+row*22,21,18,2,'#c28252');box(-51,-45,102,44,4,'#282928');for(let i=-42;i<48;i+=12){ctx.strokeStyle='#aaa58c';ctx.beginPath();ctx.moveTo(i,-41);ctx.lineTo(i,-6);ctx.stroke()}if(g.cook>0||g.ready){box(-31,-31,24,15,6,g.ready?'#b36a3c':'#d98064');box(7,-30,29,16,6,g.ready?'#b36a3c':'#d98064');ctx.fillStyle='#ebe3c855';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(-15+i*20,-61-Math.sin(performance.now()/500+i)*8,9,0,7);ctx.fill()}}}
if(s.id==='ice'){box(-49,-28,98,51,8,'#59898d');box(-54,-39,108,20,5,'#cbe5d6');for(let i=-30;i<40;i+=23){box(i,-16,16,20,4,'#c6e5de');}label('HIELO',0,17,12,'#f3f0d1');}
if(s.id==='fridge'){box(-48,-43,96,70,10,'#9b5140');box(-53,-49,106,19,5,'#de9a69');box(-38,-27,76,43,5,'#693e30');for(let i=-25;i<35;i+=20){box(i,-23,10,30,3,'#577347');box(i+2,-31,6,12,2,'#75905b')}box(-38,20,76,5,2,'#231e1b');box(-38,20,76*g.cold/100,5,2,'#9ce1cc');}
if(s.id==='seats'){for(let i=0;i<4;i++){const xx=-62+i*36;box(xx,-34,28,57,3,i<g.seats?'#dfc58b':'#8f8772');box(xx+4,-29,20,35,2,i<g.seats?'#628c79':'#766355');box(xx+2,17,4,15,1,'#513b2c');box(xx+22,17,4,15,1,'#513b2c');if(i>=g.seats)label('!',xx+14,-3,21,'#ffcd74');}}
if(s.id==='power'){box(-46,-37,92,61,7,'#be953e');box(-37,-30,41,42,5,'#343932');ctx.strokeStyle='#7d8673';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(-32,-24+i*7);ctx.lineTo(-1,-24+i*7);ctx.stroke()}box(13,-27,20,11,2,g.outage?'#8d332d':'#97b962');box(14,-6,17,17,4,'#2c332d');box(-31,-44,62,8,2,'#3a3b2c');}
if(s.id==='candles'){box(-51,-31,102,61,3,'#bc9b63');box(-59,-48,118,23,3,'#883e32');for(let i=-55;i<55;i+=23)box(i,-48,12,23,1,'#ead3a0');box(-38,-16,76,39,2,'#69543a');for(let i=-24;i<32;i+=24){box(i,-11,8,26,2,'#f6e5ac');label('🕯',i+4,-5,15,'#ffe3aa');}}
ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.restore();box(x-79,y+39,158,38,5,active?'#f1c36e':'#243a29');label(s.name,x,y+55,12,active?'#372b1e':'#f3dfab');let sub=s.id==='grill'?(g.ready?`¡LISTA! ${g.tutorial?'':Math.ceil(g.cook)+'s'}`:g.cook>0?`Cocinando ${Math.ceil(g.cook)}s`:'Dejar carne / retirar'):s.id==='fridge'?`Frío ${Math.round(g.cold)}%`:s.id==='seats'?`${g.seats}/4 reparadas`:s.id==='power'?(g.outage?'Conseguir y conectar':'Hay electricidad'):s.id==='candles'?(g.candles?'Velas encendidas':'Comprar velas'):s.id==='ice'?'Recoger bolsa':'Carne + carbón';label(sub,x,y+70,10,active?'#524028':'#b8cba5');
if(active){ctx.strokeStyle='#ffe39a';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y+5,76,50,0,0,Math.PI*2);ctx.stroke();ctx.lineWidth=1;}}
function draw(){if(!g||$('play').hidden)return;ctx.clearRect(0,0,960,560);ctx.fillStyle='#497047';ctx.fillRect(0,0,960,560);for(let x=12;x<960;x+=27)for(let y=25;y<560;y+=31){ctx.fillStyle=(x+y)%2?'#63824b':'#355d3d';ctx.fillRect(x,y,3,7)}
box(237,70,490,439,35,'#8b825d');box(247,80,470,419,28,'#b7aa7b');ctx.strokeStyle='#a59870';for(let x=255;x<720;x+=45){ctx.beginPath();ctx.moveTo(x,85);ctx.lineTo(x,490);ctx.stroke()}for(let y=90;y<500;y+=40){ctx.beginPath();ctx.moveTo(250,y);ctx.lineTo(710,y);ctx.stroke()}
for(let x=0;x<960;x+=32){box(x,0,28,38,3,'#624c32');box(x+3,3,22,26,2,'#947044')}ctx.strokeStyle='#282d23';ctx.beginPath();ctx.moveTo(0,22);ctx.quadraticCurveTo(480,110,960,22);ctx.stroke();for(let x=35;x<940;x+=65){const y=22+44*(1-Math.pow((x-480)/480,2));ctx.fillStyle=g.outage&&!g.candles?'#766d48':'#ffdf8c';ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fill()}
box(338,250,284,63,10,'#654530');box(333,240,284,62,9,'#a87343');for(let i=0;i<4;i++)box(340,245+i*13,270,2,0,'#c08b52');for(let i=0;i<5;i++){box(350+i*52,219,33,15,4,'#755637');box(350+i*52,310,33,15,4,'#755637');ctx.fillStyle='#e4d9ad';ctx.beginPath();ctx.arc(366+i*51,260,11,0,7);ctx.fill();}label('CHICHACHOS',475,292,12,'#513822');
for(const s of stations)stationArt(s,g.target?.id===s.id||(g.tutorial&&lesson[g.step]?.[0]===s.id));
// Ipa waits beside the table.
ctx.fillStyle='#8f683f';ctx.beginPath();ctx.ellipse(655,340,24,12,.2,0,7);ctx.fill();ctx.beginPath();ctx.arc(676,331,12,0,7);ctx.fill();box(666,329,7,19,4,'#5a402e');label('Ipa',656,365,10,'#36472e');
if(g.outage){ctx.fillStyle=g.candles?'#dfaa4c12':'#091d2988';ctx.fillRect(0,0,960,560)}if(g.tutorial&&lesson[g.step]){const dest=stations.find(s=>s.id===lesson[g.step][0]);label('▼ TOCÁ ACÁ',dest.x,dest.y-65-Math.sin(performance.now()/200)*4,15,'#ffe18a');}if(g.target){ctx.strokeStyle='#fce4a1';ctx.setLineDash([5,8]);ctx.beginPath();ctx.moveTo(g.x,g.y);ctx.lineTo(g.target.x,g.target.y);ctx.stroke();ctx.setLineDash([])}
ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(g.x,g.y+32,25,9,0,0,7);ctx.fill();box(g.x-13,g.y+6,26,29,8,'#d19b50');box(g.x-12,g.y+28,9,12,2,'#303d35');box(g.x+3,g.y+28,9,12,2,'#303d35');ctx.save();ctx.beginPath();ctx.arc(g.x,g.y-6,25,0,7);ctx.clip();const im=images[g.person];if(im.complete&&im.naturalWidth){const side=Math.min(im.naturalWidth,im.naturalHeight);ctx.drawImage(im,(im.naturalWidth-side)/2,0,side,side,g.x-25,g.y-31,50,50)}ctx.restore();ctx.strokeStyle=g.drunk>0?'#f76b35':'#ffe5a1';ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,g.y-6,26,0,7);ctx.stroke();ctx.lineWidth=1;label(g.person,g.x,g.y-42,13,'#fff');if(g.lock>0)label('💤 19:00',g.x,g.y-66,16,'#ffe18a');if(g.cargo.length)label(g.cargo.map(c=>c==='carne'?'📦':'🧊').join(''),g.x+30,g.y+25,18);if(g.job){box(g.x-32,g.y+47,64,7,3,'#254c3d');box(g.x-32,g.y+47,64*(1-g.job.left/g.job.total),7,3,'#ffd877')}if(g.priority>0)label(`DECRETO ACTIVO · PUNTOS ×1,5 · ${Math.ceil(g.priority)}s`,480,543,12,'#ffe5a1');}

function end(){g.done=true;keys.clear();const earned=[];if(g.food>=3&&g.drinks>=3&&g.seats>=4)earned.push('approved');if(g.drinks>=3&&g.minCold>=25)earned.push('ice');if(g.seats>=4)earned.push('seats');if(g.fixed)earned.push('power');if(g.food>=3&&g.burns===0)earned.push('chef');if(earned.includes('approved')&&earned.includes('ice')&&g.burns===0)earned.push('legend');if(g.person==='Corcho')earned.push('corcho');saved.played=[...new Set([...saved.played,g.person])];if(saved.played.length===10)earned.push('all');g.earned=earned;saved.badges=[...new Set([...saved.badges,...earned])];const record=g.score>saved.best;saved.best=Math.max(saved.best,g.score);const stored=persist();$('verdict').textContent=earned.includes('approved')?'Asado aprobado.':g.score>=1200?'Se comió igual.':'Pedimos unas pizzas.';$('result-photo').src=`characters/${g.person}.png`;$('result-photo').alt=g.person;$('result-name').textContent=`${g.person} · ${g.date}`;$('final-score').textContent=g.score.toLocaleString('es-AR');$('result-note').textContent=`${g.food} tandas · ${g.drinks} entregas de hielo · ${g.seats} reposeras. ${record?'Nuevo récord personal. ':''}${earned.includes('approved')?'La Comisión se atribuye todo el mérito.':'La Comisión convocó otra reunión.'}`;$('earned').innerHTML=earned.length?earned.map(id=>{const b=badgeDefs.find(b=>b[0]===id);return `<span class="badge">${b[1]} ${b[2]}</span>`}).join(''):'<p>Los badges esperan la próxima juntada.</p>';$('share-status').textContent=stored?'Récord y badges guardados en este navegador.':'Este navegador no permitió guardar el progreso.';show('result');}
function resultText(){return `🔥 CHICHACHOS · LA COMISIÓN\n${g.person} — ${g.score} puntos\nAsado 2026 · Desafío ${g.date}\n${g.food} tandas · ${g.drinks} hielos · ${g.seats} reposeras\n${g.earned.map(id=>badgeDefs.find(b=>b[0]===id)[2]).join(' · ')}\n¿Lo superás?`}
$('share').onclick=async()=>{const text=resultText();try{if(navigator.share)await navigator.share({title:'CHICHACHOS · La Comisión',text,...(location.protocol.startsWith('http')?{url:location.href}: {})});else if(navigator.clipboard){await navigator.clipboard.writeText(text+(location.protocol.startsWith('http')?'\n'+location.href:''));$('share-status').textContent='Resultado copiado. Pegalo en el grupo.'}else throw Error();}catch(e){$('share-status').textContent=e.name==='AbortError'?'Compartir cancelado.':'Podés descargar la tarjeta para enviarla al grupo.'}};
$('download').onclick=()=>{const c=document.createElement('canvas');c.width=1080;c.height=1080;const d=c.getContext('2d');d.fillStyle='#17382e';d.fillRect(0,0,1080,1080);d.textAlign='center';d.fillStyle='#eacb65';d.font='bold 30px sans-serif';d.fillText('CHICHACHOS · LA COMISIÓN',540,100);d.fillStyle='#f3efdf';d.font='bold 48px sans-serif';d.fillText('ASADO DE FIN DE AÑO 2026',540,170);const im=images[g.person];if(im.complete&&im.naturalWidth){d.save();d.beginPath();d.arc(540,340,105,0,Math.PI*2);d.clip();const s=Math.min(im.naturalWidth,im.naturalHeight);d.drawImage(im,(im.naturalWidth-s)/2,0,s,s,435,235,210,210);d.restore()}d.font='bold 44px sans-serif';d.fillText(g.person,540,515);d.fillStyle='#f76b35';d.font='bold 160px sans-serif';d.fillText(g.score,540,700);d.fillStyle='#f3efdf';d.font='26px sans-serif';d.fillText(`PUNTOS · DESAFÍO ${g.date}`,540,755);d.fillText(`${g.food} tandas / ${g.drinks} hielos / ${g.seats} reposeras`,540,825);d.fillStyle='#eacb65';d.font='bold 36px sans-serif';d.fillText('¿LO SUPERÁS?',540,960);const a=document.createElement('a');a.download=`chichachos-${g.person}-${g.score}.png`;a.href=c.toDataURL('image/png');a.click()};$('again').onclick=()=>{renderLobby();show('lobby')};
function frame(t){const dt=Math.min((t-last)/1000,.08);last=t;tick(dt);draw();if(t>toastUntil)$('toast').classList.remove('show');requestAnimationFrame(frame)}renderLobby();requestAnimationFrame(frame);
